import { Stage } from '../types';
import { LanguageCode } from './translations';
type StagePatch=any;
const translations:Partial<Record<LanguageCode,Record<string,StagePatch>>>={
en:{'95':{title:'95. Real-Estate Syndication, Funds & Tokenisation',subtitle:'Waterfalls, leverage, securities compliance, REITs and digital ownership records',description:'Assess syndications, funds, REITs and token structures through complete legal, tax, financing, investor and risk review. Leverage, illiquidity, construction, rent, rate, valuation and default risks remain.',lessons:{
'95.1':{stageTitle:'95. Syndication & GP/LP Structures',title:'Real-Estate Syndication: Governance, Waterfalls & Investor Protection',description:'Understand how structures allocate control, capital, fees and losses and when fundraising triggers securities, fund, distribution and AML duties.',learnContent:{videoTitle:'Masterclass: Syndication, Waterfalls & Downside Modelling',summaryText:'A GP/LP or similar structure allocates control, capital, compensation and losses by contract. Fundraising may trigger prospectus, authorisation, distribution, AML and investor duties. Waterfalls change allocation but guarantee neither preferred return nor GP profit.',bulletPoints:['Map entity, title, debt, guarantees, decision rights, conflicts and fiduciary or contractual duties','Treat preferred return as a distribution priority, not guaranteed interest','Model promote and catch-up with actual cash, clawback, conflicts and downside scenarios','Choose the offering route by jurisdiction; US Rule 506(c), German VermAnlG/WpPG/KAGB and EU routes are not interchangeable'],coreConcepts:[{iconName:'pie-chart',title:'CONDITIONAL WATERFALL',description:'Distribution priority with disclosure and no guaranteed payment.',highlight:true},{iconName:'dollar-sign',title:'ALIGNED INCENTIVES',description:'Asymmetric compensation may increase incentives and losses and requires fair disclosure.'}],resources:[{title:'Syndication Risk & Waterfall Workbook',subtitle:'PDF model for cash flow, leverage, fees, conflicts and investor rights',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'Mara CRM Investor Compliance Register',subtitle:'Track approved onboarding evidence without replacing regulated transfer agents',type:'tool',iconName:'dollar-sign',actionUrl:'crm'}],fullArticleGuide:`### Model the asset and the offering together
1. Verify title, zoning, leases, condition, environmental and development risks.
2. Model acquisition, construction, tax, capex, vacancy, rates, refinancing and exit.
3. Map debt priority, covenants, guarantees, recourse and enforcement.
4. Define governance, reserved matters, conflicts, fees, removal and reporting.
5. Calculate waterfalls from dated cash flows, including clawback and loss cases.
6. Classify the instrument, issuer, manager, distributor and target investors.
7. Select a lawful offering route in every relevant jurisdiction.
8. Implement KYC/AML, eligibility, disclosures, records, complaints and privacy.
9. Use independent legal, tax, valuation, engineering and financial review.
10. Make no promise of preferred return, valuation, refinance, liquidity or exit.

Rule 506(c) permits general solicitation only when its conditions are met, including accredited-investor verification; it is not a universal prospectus.`},understandContent:{coreTakeaway:'Syndication is regulated fundraising with contractual, governance and economic duties, not a wealth guarantee.',keyPrinciples:['Disclose fees, conflicts, assumptions and downside in comparable terms','Match financing and liquidity to stress scenarios rather than target returns']},actionTask:{instruction:'Prepare an investment-committee and offering review:',checklistItems:['Model base, downside, vacancy, rate, cost, refinance and exit cases','Map waterfall, fees, clawback, guarantees and investor rights','Obtain offering, distribution, KYC/AML, suitability and privacy review']}},
'95.2':{stageTitle:'95. Tokenisation & REIT Structures',title:'Real-Estate Tokenisation: Legal Rights, Registers & Liquidity Limits',description:'Separate technical tokens from the legal instrument, asset ownership, regulated offer, custody, transfer and secondary market.',learnContent:{videoTitle:'Masterclass: Tokenisation, REITs & Securities Infrastructure',summaryText:'Tokenisation digitises rights or records but does not remove securities, fund, prospectus, distribution, tax, land-register or AML duties. A standard creates no authorised market, worldwide selling permission or liquidity.',bulletPoints:['ERC-3643 is a technical permissioned-token standard; legal rights and identity controls require case-specific implementation','REIT rules differ by jurisdiction; do not mix German REIT-AG, US REIT or other regimes','Secondary trading requires lawful transfer, an authorised venue where needed, buyers, price discovery, custody and compliance','Distributions require decisions, available funds, tax, register and payment processes; code does not replace them'],coreConcepts:[{iconName:'lock',title:'RIGHTS BEFORE TOKENS',description:'Investor rights arise from law and documents, not from a token label.',highlight:true},{iconName:'repeat',title:'LIQUIDITY IS NOT CODE',description:'Transferability does not guarantee a market, price, buyer or settlement.'}],resources:[{title:'Tokenisation Legal-Architecture Workbook',subtitle:'PDF for instrument, issuer, SPV, register, custody, transfer and offering route',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'GOM-MAR Tokenisation Sandbox',subtitle:'Model test records without issuing or distributing live securities',type:'tool',iconName:'award',actionUrl:'settings'}],fullArticleGuide:`### Build the legal architecture before the token
1. Define the property, issuer, SPV, instrument and investor claim.
2. Verify title, security, insolvency rank, governance and cash waterfall.
3. Classify security, fund interest, crypto-asset or other instrument in each jurisdiction.
4. Determine prospectus, information-document, exemption and marketing rules.
5. Select lawful register, custody, transfer-agent and identity arrangements.
6. Design KYC/AML, sanctions, eligibility, privacy and investor-right controls.
7. Verify trading-venue, settlement and cross-border distribution permissions.
8. Audit code, administrators, upgrades, keys, recovery and reconciliation.
9. Explain fees, illiquidity, valuation, dilution, tax and technology failure.
10. Test operations without presenting a sandbox as an approved issuance platform.

Tokenisation does not replace a land register, notarial form where required, insolvency analysis or regulated market infrastructure.`,},understandContent:{coreTakeaway:'Tokenisation may change administration and transfer, not automatically stability, liquidity or investor protection.',keyPrinciples:['Classify the instrument and offering route before selecting technology','Verify SPV, title, security, rank, governance and investor rights independently']},actionTask:{instruction:'Prepare a tokenisation feasibility memorandum:',checklistItems:['Map asset, SPV, instrument, register, custody, transfer and investor claim','Determine prospectus, fund, securities, crypto, distribution and tax duties','Model liquidity failure, cyber, key, administrator, insolvency and reconciliation risks']}}}}},
pl:{'95':{title:'95. Syndykacja nieruchomości, fundusze i tokenizacja',subtitle:'Waterfalls, leverage, securities compliance, REIT i digital records',description:'Oceniaj syndication, funds, REIT i token structures przez legal, tax, financing, investor i risk review. Leverage, illiquidity, construction, rent, rates, valuation i default pozostają.',lessons:{
'95.1':{stageTitle:'95. Syndication i GP/LP',title:'Syndykacja: governance, waterfall i investor protection',description:'Poznaj allocation control, capital, fees i losses oraz obowiązki fundraising.',learnContent:{videoTitle:'Masterclass: syndication, waterfall i downside',summaryText:'GP/LP dzieli control, capital, compensation i losses przez contract. Fundraising może uruchamiać prospectus, authorisation, distribution, AML i investor duties. Waterfall nie gwarantuje preferred return ani GP profit.',bulletPoints:['Mapuj entity, title, debt, guarantees, decisions, conflicts i duties','Preferred return to distribution priority, nie guaranteed interest','Modeluj promote, catch-up, clawback, conflicts i downside','Wybierz offering route według jurisdiction; Rule 506(c), VermAnlG/WpPG/KAGB i EU routes nie są wymienne'],coreConcepts:[{iconName:'pie-chart',title:'WARUNKOWY WATERFALL',description:'Priority bez gwarancji payment.',highlight:true},{iconName:'dollar-sign',title:'INCENTIVES I CONFLICTS',description:'Asymmetric fees wymagają disclosure.'}],resources:[{title:'Workbook syndication i waterfall',subtitle:'PDF dla cash flow, leverage, fees, conflicts i rights',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'Mara CRM Investor Compliance Register',subtitle:'Śledź approved onboarding evidence',type:'tool',iconName:'dollar-sign',actionUrl:'crm'}],fullArticleGuide:`### Modeluj asset i offering razem
1. Sprawdź title, zoning, leases, condition i development risks.
2. Modeluj acquisition, construction, tax, vacancy, rates, refinance i exit.
3. Mapuj debt priority, covenants, guarantees i enforcement.
4. Zdefiniuj governance, conflicts, fees, removal i reporting.
5. Licz waterfall z dated cash flow, clawback i loss cases.
6. Klasyfikuj instrument, issuer, manager i distributor.
7. Wybierz lawful offering route w każdej jurisdiction.
8. Wdróż KYC/AML, eligibility, disclosures, complaints i privacy.
9. Uzyskaj independent legal, tax, valuation i engineering review.
10. Nie gwarantuj return, valuation, refinance, liquidity ani exit.`},understandContent:{coreTakeaway:'Syndication to regulated fundraising, nie wealth guarantee.',keyPrinciples:['Disclose fees, conflicts, assumptions i downside','Dopasuj financing do stress scenarios']},actionTask:{instruction:'Przygotuj investment review:',checklistItems:['Modeluj base, downside, vacancy, rate, cost, refinance i exit','Mapuj waterfall, fees, clawback, guarantees i rights','Uzyskaj offering, distribution, KYC/AML, suitability i privacy review']}},
'95.2':{stageTitle:'95. Tokenisation i REIT',title:'Tokenizacja: legal rights, registers i liquidity limits',description:'Oddziel technical token od legal instrument, ownership, regulated offer, custody, transfer i market.',learnContent:{videoTitle:'Masterclass: tokenisation, REIT i securities infrastructure',summaryText:'Tokenizacja digitalizuje rights lub records, lecz nie usuwa securities, fund, prospectus, distribution, tax, land-register ani AML duties. Standard nie tworzy market, worldwide permission ani liquidity.',bulletPoints:['ERC-3643 to technical standard; legal rights i identity wymagają implementation','REIT rules zależą od jurisdiction','Secondary trading wymaga lawful transfer, venue, buyers, pricing, custody i compliance','Distributions wymagają decisions, funds, tax, register i payment'],coreConcepts:[{iconName:'lock',title:'RIGHTS BEFORE TOKENS',description:'Rights wynikają z law i documents.',highlight:true},{iconName:'repeat',title:'LIQUIDITY IS NOT CODE',description:'Transferability nie gwarantuje buyer lub price.'}],resources:[{title:'Workbook legal architecture tokenisation',subtitle:'PDF dla instrument, issuer, SPV, register, custody i offering',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'GOM-MAR Tokenisation Sandbox',subtitle:'Modeluj test records bez live issuance',type:'tool',iconName:'award',actionUrl:'settings'}],fullArticleGuide:`### Legal architecture przed tokenem
1. Zdefiniuj property, issuer, SPV, instrument i investor claim.
2. Sprawdź title, security, rank, governance i waterfall.
3. Klasyfikuj instrument w każdej jurisdiction.
4. Ustal prospectus, exemption i marketing rules.
5. Wybierz lawful register, custody i transfer arrangements.
6. Zaprojektuj KYC/AML, sanctions, eligibility i privacy.
7. Sprawdź venue, settlement i cross-border permissions.
8. Audituj code, admins, upgrades, keys i recovery.
9. Wyjaśnij fees, illiquidity, valuation, tax i failure.
10. Nie przedstawiaj sandbox jako approved platform.`},understandContent:{coreTakeaway:'Tokenisation zmienia administration, nie automatycznie stability, liquidity lub protection.',keyPrinciples:['Klasyfikuj instrument przed technology','Zweryfikuj SPV, title, security, rank i rights']},actionTask:{instruction:'Przygotuj feasibility memo:',checklistItems:['Mapuj asset, SPV, instrument, register, custody i claim','Ustal prospectus, fund, securities, crypto, distribution i tax','Modeluj liquidity, cyber, key, admin, insolvency i reconciliation risks']}}}}}
};
export const localizeAcademyStage95=(stages:Stage[],language:LanguageCode):Stage[]=>{const p=translations[language]?.['95'];if(!p)return stages;return stages.map(s=>s.id!==95?s:({...s,...p,lessons:s.lessons.map(l=>{const q=p.lessons?.[l.id];return !q?l:({...l,...q,learnContent:{...l.learnContent,...q.learnContent},understandContent:{...l.understandContent,...q.understandContent},actionTask:{...l.actionTask,...q.actionTask}})})}))};
