import { Stage } from '../types';
import { LanguageCode } from './translations';
type StagePatch=any;
const translations:Partial<Record<LanguageCode,Record<string,StagePatch>>>={
en:{'94':{title:'94. Defence, Dual-Use Technology & Security Procurement',subtitle:'Export control, sanctions, NCAGE, classified work and critical infrastructure',description:'Assess security-related technology business through qualified legal and compliance review. Classify items and transactions, review end use, sanctions, authorisations, procurement, security and critical-infrastructure requirements without promising access or awards.',lessons:{
'94.1':{stageTitle:'94. Dual-Use & Export Control',title:'Dual-Use Technology, Authorisations & Transaction Due Diligence',description:'Classify hardware, software, technology and services and review destinations, parties, end use, sanctions and authorisations.',learnContent:{videoTitle:'Masterclass: EU Dual-Use Compliance & Export Governance',summaryText:'Not every AI, drone or surveillance technology is automatically listed, while unlisted items may face catch-all, sanctions or end-use controls. Duties and consequences depend on the item, transaction, destination, parties, end use and fault.',bulletPoints:['Use the current consolidated Regulation (EU) 2021/821: Annex I, catch-all, cyber-surveillance, brokering, technical assistance, transit and intra-EU transfer','Use the competent authority portal and obtain classification or authorisation guidance where appropriate','Treat end-use documents as evidence, not a guarantee; test parties, ownership, control, diversion, red flags and actual use','Screen applicable sanctions regimes with documented matching, escalation, re-screening and legal review'],coreConcepts:[{iconName:'shield',title:'RISK-BASED ICP',description:'An internal compliance programme reduces risk but guarantees neither authorisation nor immunity.',highlight:true},{iconName:'user-check',title:'EXPLAINABLE SCREENING',description:'Review relevant lists, ownership, control, aliases, matches and changes with human escalation.'}],resources:[{title:'Export-Control Transaction Workbook',subtitle:'PDF for classification, parties, destinations, end use, licences and records',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'Mara CRM Compliance Case Register',subtitle:'Record approved screening evidence and escalation without making legal decisions',type:'tool',iconName:'shield',actionUrl:'settings'}],fullArticleGuide:`### A defensible export-control workflow
1. Identify exporter, items, software, technology, services and transaction route.
2. Classify against current EU and national control lists with evidence.
3. Review catch-all, cyber-surveillance, military, WMD and human-rights red flags.
4. Screen parties, beneficial ownership, control, banks, carriers and destinations.
5. Verify end user, intermediaries, end use, installation, support and diversion risk.
6. Determine competent authority and the required individual, global or general authorisation.
7. Follow licence conditions, reporting, customs and post-shipment duties.
8. Apply stop-ship, escalation and four-eyes approval before release.
9. Re-screen when parties, law, ownership, route, item or end use changes.
10. Retain records for the periods required by applicable EU, national, customs, licence and privacy law.

An end-use certificate, software result or prior authorisation never replaces case-specific due diligence.`,resources:undefined},understandContent:{coreTakeaway:'Export control is an ongoing corporate duty, not a sales certificate or procurement advantage.',keyPrinciples:['Use case-specific authorisation, end-use review and four-eyes release','Set retention from the rules actually applicable to the transaction']},actionTask:{instruction:'Design an auditable export-control procedure:',checklistItems:['Document item and technology classification with reviewer and date','Review parties, ownership, control, countries, banks, transport and red flags','Define authorisation, end use, escalation, stop-ship, records and re-screening']}},
'94.2':{stageTitle:'94. NCAGE, Classified Work & Critical Infrastructure',title:'Security Procurement: NCAGE, NSPA Registration & Eligibility',description:'Separate NCAGE identification, NSPA registration, procurement eligibility, personnel vetting and facility security without promising contract access.',learnContent:{videoTitle:'Masterclass: NATO Procurement & Security Governance',summaryText:'An NCAGE code primarily identifies an entity in the NATO codification system. It is not certification, clearance or contract approval. NSPA solicitation participation also requires registration in the NSPA Source File, and every procedure has separate eligibility, security and compliance terms.',bulletPoints:['NCAGE is an identification code, not a quality certificate or automatic supplier approval','Personnel vetting follows competent authority, role, classification and need-to-know; employers cannot promise clearance','Check the NSPA Source File, eProcurement registration and solicitation-specific eligibility separately','Assess current national and EU critical-infrastructure, cybersecurity, supply-chain and incident obligations for the actual role'],coreConcepts:[{iconName:'award',title:'IDENTIFICATION, NOT CERTIFICATION',description:'NCAGE supports codification and does not guarantee eligibility, access or awards.',highlight:true},{iconName:'lock',title:'NEED-TO-KNOW',description:'Vetting and access depend on authority, contract, classification, role and continuing duties.'}],resources:[{title:'Security-Procurement Go/No-Go Workbook',subtitle:'PDF for registration, eligibility, exclusion, security and bid controls',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'GOM-MAR Sensitive-Project Control Register',subtitle:'Track approved roles and handling rules; not a system for classified information',type:'tool',iconName:'shield',actionUrl:'settings'}],fullArticleGuide:`### Treat each procurement as a separate controlled case
1. Read the notice, contracting authority, jurisdiction and complete terms.
2. Confirm whether NCAGE, NSPA Source File, SAM.gov or another registration is actually required.
3. Verify financial, technical, past-performance and exclusion criteria.
4. Map export-control, sanctions, anti-bribery, lobbying and conflict rules.
5. Determine personnel, facility, information and supply-chain security requirements.
6. Do not collect or store classified material in unapproved systems.
7. Price security, audit, localisation, insurance, reporting and flow-down obligations.
8. Protect competition-sensitive information and document bid decisions.
9. Make no public claim about protected work without contractual and authority approval.
10. Submit only when evidence supports every representation.

An identifier or registration does not confer NATO approval or a right to bid, win or access classified information.`},understandContent:{coreTakeaway:'NCAGE addresses identification; competition, eligibility, registration, security and performance remain separate.',keyPrinciples:['Apply security rules and need-to-know without public boasting','Maintain briefings, clearances, reporting and controls with competent authorities']},actionTask:{instruction:'Prepare a go/no-go review for one solicitation:',checklistItems:['Verify the actual identifier, portal, eligibility and exclusion requirements','Map export control, security, cybersecurity, supply chain and data location','Document owners, evidence, representations, bid risks and approval']}}}}},
pl:{'94':{title:'94. Obrona, dual-use technology i security procurement',subtitle:'Export control, sankcje, NCAGE, classified work i critical infrastructure',description:'Oceniaj security technology przez legal i compliance review. Klasyfikuj items i transactions, end use, sanctions, authorisations, procurement i security bez obietnicy dostępu lub kontraktu.',lessons:{
'94.1':{stageTitle:'94. Dual-use i export control',title:'Dual-use technology, authorisations i transaction due diligence',description:'Klasyfikuj hardware, software, technology i services oraz destination, parties, end use, sanctions i authorisations.',learnContent:{videoTitle:'Masterclass: EU dual-use compliance i export governance',summaryText:'Nie każda AI, drone lub surveillance technology jest listed, a unlisted items mogą podlegać catch-all, sanctions lub end-use controls. Obowiązki zależą od item, transaction, destination, parties, end use i fault.',bulletPoints:['Stosuj aktualne rozporządzenie (UE) 2021/821: Annex I, catch-all, cyber-surveillance, brokering, technical assistance, transit i transfer','Korzystaj z właściwego authority portal i classification lub authorisation guidance','End-use documents to evidence, nie guarantee; sprawdzaj parties, ownership, control, diversion i actual use','Screen applicable sanctions z matching, escalation, re-screening i legal review'],coreConcepts:[{iconName:'shield',title:'RISK-BASED ICP',description:'ICP ogranicza ryzyko, ale nie gwarantuje authorisation ani immunity.',highlight:true},{iconName:'user-check',title:'EXPLAINABLE SCREENING',description:'Sprawdzaj lists, ownership, control, aliases, matches i changes z human escalation.'}],resources:[{title:'Workbook transakcji export-control',subtitle:'PDF dla classification, parties, destinations, end use, licences i records',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'Mara CRM Compliance Case Register',subtitle:'Zapisuj approved evidence i escalation bez decyzji prawnych',type:'tool',iconName:'shield',actionUrl:'settings'}],fullArticleGuide:`### Defensible export-control workflow
1. Zidentyfikuj exporter, items, software, technology, services i route.
2. Klasyfikuj według aktualnych list EU i national z evidence.
3. Sprawdź catch-all, cyber-surveillance, military, WMD i human-rights red flags.
4. Screen parties, beneficial ownership, control, banks, carriers i destinations.
5. Zweryfikuj end user, intermediaries, end use, support i diversion.
6. Ustal competent authority i rodzaj authorisation.
7. Spełnij licence conditions, reporting, customs i post-shipment duties.
8. Stosuj stop-ship, escalation i four-eyes approval.
9. Re-screen po zmianie parties, law, ownership, route, item lub use.
10. Retain records według applicable EU, national, customs, licence i privacy law.

EUC, wynik software lub wcześniejsza licence nie zastępują case-specific due diligence.`},understandContent:{coreTakeaway:'Export control to ciągły obowiązek, nie sales certificate.',keyPrinciples:['Stosuj case-specific authorisation, end-use review i four-eyes release','Retention wynika z zasad applicable do transaction']},actionTask:{instruction:'Zaprojektuj auditable export-control procedure:',checklistItems:['Udokumentuj classification z reviewer i date','Sprawdź parties, ownership, control, countries, banks, transport i red flags','Zdefiniuj authorisation, end use, escalation, stop-ship, records i re-screening']}},
'94.2':{stageTitle:'94. NCAGE, classified work i infrastructure',title:'Security procurement: NCAGE, NSPA registration i eligibility',description:'Oddziel NCAGE identification, NSPA registration, procurement eligibility, vetting i facility security bez obietnicy dostępu.',learnContent:{videoTitle:'Masterclass: NATO procurement i security governance',summaryText:'NCAGE przede wszystkim identyfikuje entity w NATO codification. Nie jest certification, clearance ani contract approval. NSPA wymaga też Source File registration, a każde postępowanie ma własne eligibility i security terms.',bulletPoints:['NCAGE to identification code, nie quality certificate ani supplier approval','Vetting zależy od authority, role, classification i need-to-know; employer nie gwarantuje clearance','Sprawdź NSPA Source File, eProcurement i solicitation eligibility osobno','Oceń current national i EU critical-infrastructure, cybersecurity i supply-chain duties'],coreConcepts:[{iconName:'award',title:'IDENTIFICATION, NIE CERTIFICATION',description:'NCAGE wspiera codification, bez guarantee eligibility, access lub award.',highlight:true},{iconName:'lock',title:'NEED-TO-KNOW',description:'Vetting i access zależą od authority, contract, classification i role.'}],resources:[{title:'Workbook go/no-go security procurement',subtitle:'PDF dla registration, eligibility, exclusion, security i bid controls',type:'pdf',iconName:'file-text',actionUrl:'tools'},{title:'GOM-MAR Sensitive-Project Control Register',subtitle:'Śledź approved roles; nie przechowuj classified information',type:'tool',iconName:'shield',actionUrl:'settings'}],fullArticleGuide:`### Każdy procurement to oddzielny controlled case
1. Przeczytaj notice, authority, jurisdiction i terms.
2. Potwierdź wymaganie NCAGE, NSPA Source File, SAM.gov lub innej registration.
3. Zweryfikuj financial, technical, past performance i exclusion criteria.
4. Mapuj export control, sanctions, anti-bribery, lobbying i conflicts.
5. Ustal personnel, facility, information i supply-chain security.
6. Nie przechowuj classified material w unapproved systems.
7. Wyceń security, audit, localisation, insurance, reporting i flow-down.
8. Chroń competition-sensitive information i dokumentuj bid decisions.
9. Nie publikuj protected work bez approval.
10. Submit tylko z evidence dla representations.

Identifier lub registration nie daje NATO approval, prawa do bid, win ani classified access.`},understandContent:{coreTakeaway:'NCAGE rozwiązuje identification; competition, eligibility, registration, security i performance są osobne.',keyPrinciples:['Stosuj security i need-to-know','Utrzymuj briefings, clearances, reporting i controls z authorities']},actionTask:{instruction:'Przygotuj go/no-go review dla jednej solicitation:',checklistItems:['Sprawdź identifier, portal, eligibility i exclusion','Mapuj export control, security, cybersecurity, supply chain i data location','Udokumentuj owners, evidence, representations, risks i approval']}}}}}
};
if (translations.en?.['94']) {
  translations.en['94'].lessons['94.1'].learnContent.resources = [
    { title:'Export-Control Transaction Workbook',subtitle:'PDF for classification, parties, destinations, end use, licences and records',type:'pdf',iconName:'file-text',actionUrl:'tools' },
    { title:'Mara CRM Compliance Case Register',subtitle:'Record approved screening evidence and escalation without making legal decisions',type:'tool',iconName:'shield',actionUrl:'settings' },
  ];
}
export const localizeAcademyStage94=(stages:Stage[],language:LanguageCode):Stage[]=>{const p=translations[language]?.['94'];if(!p)return stages;return stages.map(s=>s.id!==94?s:({...s,...p,lessons:s.lessons.map(l=>{const q=p.lessons?.[l.id];return !q?l:({...l,...q,learnContent:{...l.learnContent,...q.learnContent},understandContent:{...l.understandContent,...q.understandContent},actionTask:{...l.actionTask,...q.actionTask}})})}))};
