import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const server = readFileSync('server.ts', 'utf8');
const connection = readFileSync('server/instagramConnectionAdmin.ts', 'utf8');
const client = readFileSync('src/services/instagramService.ts', 'utf8');
const modal = readFileSync('src/components/ContentEngine/InstagramPublishModal.tsx', 'utf8');
const instagramTab = readFileSync('src/components/ContentEngine/InstagramPostsTab.tsx', 'utf8');
const pins = readFileSync('src/components/ContentEngine/PinterestPinsTab.tsx', 'utf8');
const legal = readFileSync('src/components/LegalModal.tsx', 'utf8');
const publicPrivacy = readFileSync('public/privacy/index.html', 'utf8');

assert.match(server, /app\.post\('\/api\/instagram\/oauth\/start', requireVerifiedMember, requireProMember/, 'Instagram OAuth muss geschützt sein.');
assert.match(server, /app\.get\('\/api\/instagram\/oauth\/callback'/, 'Der Instagram OAuth-Callback fehlt.');
assert.match(server, /app\.post\('\/api\/instagram\/publish-image', requireVerifiedMember, requireProMember/, 'Instagram-Veröffentlichungen müssen geschützt sein.');
assert.match(server, /app\.get\('\/api\/instagram\/media\/:token'/, 'Instagram benötigt einen kurzlebigen öffentlichen Bildabruf.');
assert.match(connection, /LESSON_AUDIO_BUCKET/, 'Der bewährte private Medien-Bucket muss als Fallback genutzt werden.');
assert.match(connection, /instagram-media:/, 'Instagram-Bildadressen müssen signiert sein.');
assert.match(connection, /instagramMediaUrlMaxAgeMs/, 'Instagram-Bildadressen müssen zeitlich begrenzt sein.');
assert.match(connection, /createCipheriv\('aes-256-gcm'/, 'Instagram-Tokens müssen verschlüsselt gespeichert werden.');
assert.match(connection, /academyInstagramConnections/, 'Instagram-Verbindungen müssen serverseitig gespeichert werden.');
assert.match(connection, /ig_exchange_token/, 'Kurzlebige Instagram-Tokens müssen in langlebige Tokens umgewandelt werden.');
assert.match(connection, /ig_refresh_token/, 'Instagram-Tokens müssen automatisch erneuert werden.');
assert.match(connection, /instagram_business_content_publish/, 'Die Veröffentlichungsberechtigung fehlt.');
assert.match(connection, /media_publish/, 'Die echte Instagram-Veröffentlichung fehlt.');
assert.match(connection, /waitForInstagramMedia/, 'Vor der Veröffentlichung muss die Instagram-Medienverarbeitung abgewartet werden.');
assert.match(connection, /status_code === 'FINISHED'/, 'Instagram darf erst nach vollständig verarbeiteter Grafik veröffentlichen.');
assert.match(connection, /status_code === 'ERROR'/, 'Fehler bei der Instagram-Medienverarbeitung müssen erkannt werden.');
assert.match(client, /authenticatedFetch\('\/api\/instagram\/oauth\/start'/, 'Der Browser muss den geschützten OAuth-Start verwenden.');
assert.doesNotMatch(client, /client_secret|access_token/i, 'Instagram-Geheimnisse dürfen nicht in den Browser gelangen.');
assert.match(modal, /Instagram verbinden/, 'Die Oberfläche muss eine Instagram-Verbindung anbieten.');
assert.match(modal, /width: 1080, height: 1350/, 'Instagram-Grafiken müssen im Feed-Format 4:5 erstellt werden.');
assert.match(modal, /aspect-\[4\/5\]/, 'Die Instagram-Vorschau muss das Feed-Format 4:5 zeigen.');
assert.doesNotMatch(pins, /Auf Instagram posten/, 'Pinterest- und Instagram-Veröffentlichung müssen getrennte Bereiche haben.');
assert.match(instagramTab, /Auf Instagram veröffentlichen/, 'Der getrennte Instagram-Bereich muss eine Veröffentlichung anbieten.');
assert.match(instagramTab, /width: 1080, height: 1350/, 'Der Instagram-Bereich muss im Format 4:5 rendern.');
assert.match(legal, /Instagram-Verbindung/, 'Die interne Datenschutzerklärung muss Instagram erläutern.');
assert.match(publicPrivacy, /Instagram-Verbindung/, 'Die öffentliche Datenschutzerklärung muss Instagram erläutern.');

console.log('Instagram-Automatisierung geprüft: OAuth, verschlüsselte Tokens und echte Bildveröffentlichung sind vorbereitet.');
